import streamlit as st
from PIL import Image

def show_about_page():
    with st.container():
        yol = "HTML/container_background.html"
        f = open(yol, 'r')
        contents = f.read()
        f.close()
        contents = contents.replace('smth', 'About')
        st.markdown(contents, unsafe_allow_html=True)
    st.write("This **Pneu-will-know** web app is the final product of my Data Science Project. "
             "It is mainly used to predict pneumonia based on uploaded chest X-ray image and "
             "present a dashboard about global pneumonia statistics.")

    # st.write("""### Problem Statement: """)
    font_color("Problem Statement")
    st.write(" 1. Shortage of radiologists especially in rural areas.")
    st.write("2. Late discovery of pneumonia may subsequently cause severe symptoms and can be fatal.")
    st.write("3. Diagnosis of pneumonia based on CXR images is subjected to considerable variability by different radiologists.")
    st.write("""***""")

    # st.write("""### Objective:""")
    font_color("Objective: ")
    st.write("1. To study, compare and evaluate existing pneumonia detection projects.")
    st.write("2. To train a model to predict diagnosis of pneumonia based on chest X-ray images.")
    st.write("3. To present a dashboard about pneumonia disease to raise awareness about pneumonia disease among Malaysians.")
    st.write("""***""")

    font_color("Target Users: ")
    st.write("##### 1. Doctors/ Radiologists")
    st.write("Doctors or radiologists can use the Prediction Model page to predict the probability of a patient "
             "getting pneumonia by uploading the his or her chest X-ray image. The result generated by the Prediction Model can act as reference in the diagnosis.")
    st.write("##### 2. General public")
    st.write("The general public can obtain basic understanding about pneumonia from Home page. "
             "They can also learn about the statistics of pneumonia from the Dashboard page."
             "Overall, it can raise awareness about pneumonia among the public.")
    st.write("""***""")

    # st.write("""### Data Source:""")
    font_color("Data Source: ")
    st.write("""##### 1. Model Training:""")
    st.write("The dataset used to train the model is obtained from [Kaggle website](https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia).")
    data_img = Image.open("images/Data source image.png")
    st.image(data_img, use_column_width=True)
    st.write("""##### 2. Dashboard:""")
    st.write("The datasets used to build dashboard is obtained from [Our World in Data website](https://ourworldindata.org/pneumonia#licence).")
    dashboard_data_img = Image.open("images/Dashboard data source.png")
    st.image(dashboard_data_img, use_column_width=True)
    st.write("""***""")

    # st.write("""### Source Code:""")
    font_color("Source Code: ")
    st.write("Kindly visit my Github to get the [source code](https://github.com/ooihuien/Pneu-will-know) ^^")
    st.write("""***""")

    # st.write("""### About Me:""")
    font_color("About Me: ")
    col1, col2 = st.columns([2,3])
    with col1:
        huien = Image.open("images/newyear 2020.jpeg")
        st.image(huien, width=180)
    with col2:
        st.write("Hi, I am Ooi Hui En, Year 3 Bachelor's of Computer Science (Data Science) student from University of Malaya.\n"
                 "Reach me at my [Github](https://github.com/ooihuien) and [LinkedIn](https://www.linkedin.com/in/hui-en-o-0504ba165/)!")


def font_color(text):
    yol = "HTML/text_color.html"
    f = open(yol, 'r')
    contents = f.read()
    f.close()
    contents = contents.replace('smth', text)
    st.markdown(contents, unsafe_allow_html=True)
